In [1]:
!pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from statsmodels) (1.16.2)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\convenience\desktop\python_assignments\asng\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [3]:
data = pd.read_csv(r"IT_salaries.csv")
data.head()

       S  X  E  M
0  13876  1  1  1
1  11608  1  3  0
2  18701  1  3  1
3  11283  1  2  0
4  11767  1  3  0

In [4]:
# FORMULA FOR OLS
# S is the column s,, M is the column M ,, and X is column X
# S: This is the dependent variable (also called the response or outcome variable).
# ~: Separates the dependent variable (S) from the independent variables (predictors).
# C(E): Treat E as a categorical variable.
# C(M): Treat M as a categorical variable.
# X: Treat X as a numerical (continuous) variable.
formula = 'S~ C(E) + C(M) + X'

In [5]:
#.fit(): This tells Python to actually fit (train) the model using the data
#It finds the best coefficients (weights) for the variables to predict S.
# ols is ordinary least squares
lm = ols(formula, data).fit()

In [6]:
# model summary
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      S   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.953
Method:                 Least Squares   F-statistic:                     226.8
Date:                Mon, 17 Nov 2025   Prob (F-statistic):           2.23e-27
Time:                        10:39:56   Log-Likelihood:                -381.63
No. Observations:                  46   AIC:                             773.3
Df Residuals:                      41   BIC:                             782.4
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   8035.5976    386.689     20.781      0.000    7254.663    8816.532
C(E)[T.2]   3144.0352    361.968      8.686      0.000    2413.025    3875.045
C(E)[T.3]   2996.2103    411.753      7.277      0.000    2164.659    3827.762
C(M)[T.1]   6883.5310    313.919     21.928      0.000    6249.559    7517.503
X            546.1840     30.519     17.896      0.000     484.549     607.819
==============================================================================
Omnibus:                        2.293   Durbin-Watson:                   2.237
Prob(Omnibus):                  0.318   Jarque-Bera (JB):                1.362
Skew:                          -0.077   Prob(JB):                        0.506
Kurtosis:                       2.171   Cond. No.                         33.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [7]:
# lm is the linear model created earlier
# typ=2 Tests each variable after adjusting for all other variables except interactions.
table = sm.stats.anova_lm(lm,typ=2)
table

                sum_sq    df           F        PR(>F)
C(E)      9.152624e+07   2.0   43.351589  7.672450e-11
C(M)      5.075724e+08   1.0  480.825394  2.901444e-24
X         3.380979e+08   1.0  320.281524  5.546313e-21
Residual  4.328072e+07  41.0         NaN           NaN

### Question 1
Scenario: A company ran three online ad campaigns — A, B, and C. You have conversion rates (%) from 10 cities for each campaign. Task: Write Python code to check if the mean conversion rates differ significantly among the campaigns using one-way ANOVA. -- # Sample data campaign_A = [12, 15, 14, 10, 13, 15, 11, 14, 13, 16] campaign_B = [18, 17, 16, 15, 20, 19, 18, 16, 17, 19] campaign_C = [10, 9, 11, 10, 12, 9, 11, 8, 10, 9]

In [8]:
# Sample data
# The F-statistic is a ratio of "between-group variance" to "within-group variance".
from scipy.stats import f_oneway
import numpy as np

campaign_A = [12, 15, 14, 10, 13, 15, 11, 14, 13, 16]
campaign_B = [18, 17, 16, 15, 20, 19, 18, 16, 17, 19]
campaign_C = [10, 9, 11, 10, 12, 9, 11, 8, 10, 9]

f_stats, p_value = f_oneway(campaign_A,campaign_B,campaign_C)
print(f_stats, p_value)
alpha = 0.05

if p_value < alpha:
    print ("reject the null hypothesis")
else:
    print ("fail to reject null hypothesis")

57.973333333333386 1.692627434604139e-10
reject the null hypothesis

### Question 2
Fertilizer Type vs Crop Yield Scenario: Three fertilizers (A, B, and C) are used on crops. You record the yield (in kg) from 8 plots for each fertilizer. Task: Perform one-way ANOVA in Python to test if fertilizer type affects crop yield. fertilizer_A = [25, 27, 26, 30, 29, 28, 30, 27] fertilizer_B = [32, 35, 34, 33, 36, 34, 35, 32] fertilizer_C = [22, 20, 24, 23, 25, 21, 22, 23] Question: Which fertilizer(s) seem to produce significantly different yields?

In [9]:
import numpy as np
from scipy.stats import f_oneway

fertilizer_A = [25, 27, 26, 30, 29, 28, 30, 27]
fertilizer_B = [32, 35, 34, 33, 36, 34, 35, 32]
fertilizer_C = [22, 20, 24, 23, 25, 21, 22, 23]

f_stats2, p_value2 = f_oneway(fertilizer_A,fertilizer_B,fertilizer_C)
print (f_stats2, p_value2)
alpha = 0.05
altern_hypotheis = "the mean differs significantly between fertilizers"
nul_hypothesis = "the mean does not differ significantly between fertilizers"

if p_value2<alpha:
    print (f"based on the current evidence {altern_hypotheis}")
else:
    print (f"based on the current evidence {nul_hypothesis}")

96.58758314855855 2.5717391158818948e-11
based on the current evidence the mean differs significantly between fertilizers

In [10]:
# checking the mean difference between machines
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Combine data and labels
yield_data = fertilizer_A + fertilizer_B + fertilizer_C
fertilizers = ['A']*len(fertilizer_A) + ['B']*len(fertilizer_B) + ['C']*len(fertilizer_C)

df = pd.DataFrame({'fertilizer': fertilizers, 'yield': yield_data})

# Tukey HSD test
tukey = pairwise_tukeyhsd(endog=df['yield'], groups=df['fertilizer'], alpha=0.05)
print(tukey)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj  lower    upper  reject
----------------------------------------------------
     A      B    6.125   0.0   4.0601  8.1899   True
     A      C    -5.25   0.0  -7.3149 -3.1851   True
     B      C  -11.375   0.0 -13.4399 -9.3101   True
----------------------------------------------------


### Question 3
Teaching Method vs Student Performance Scenario: Students were taught using three different teaching methods (Lecture, Group Discussion, and Project-based). You have their exam scores. Task: Use Python to run ANOVA and check if the teaching method affects scores. Question: Does the teaching method have a statistically significant effect on student performance?

In [11]:
data = {
    'score': [78, 85, 80, 90, 88, 82, 84, 86, 92],
    'method': ['Lecture', 'Lecture', 'Lecture',
               'Discussion', 'Discussion', 'Discussion',
               'Project', 'Project', 'Project']
}

In [12]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
df = pd.DataFrame(data)
df.head(10)

   score      method
0     78     Lecture
1     85     Lecture
2     80     Lecture
3     90  Discussion
4     88  Discussion
5     82  Discussion
6     84     Project
7     86     Project
8     92     Project

In [13]:
formula1 = 'score ~ C(method)'

In [14]:
lm2 = ols(formula1, df).fit()
lm2

In [15]:
table1 = sm.stats.anova_lm(lm2,typ=2)
table1

              sum_sq   df         F    PR(>F)
C(method)  72.666667  2.0  2.286713  0.182729
Residual   95.333333  6.0       NaN       NaN

In [16]:
alpha = 0.05
p_value = table1['PR(>F)'][0]

if p_value < alpha:
    print("based on the current evidence the teaching method has a statistically significant effect on student performance.")
else:
    print("based on the current evidence the teaching method does not have a statistically significant effect on student performance.")

based on the current evidence the teaching method does not have a statistically significant effect on student performance.

C:\Users\Convenience\AppData\Local\Temp\ipykernel_5760\18854771.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p_value = table1['PR(>F)'][0]

Question 4
Machine Type vs Production Quality Scenario: Three different machines produce the same product. You record quality scores for items from each machine. Task: Run ANOVA in Python to check if the mean quality differs among machines. Question: Which machine produces items with significantly different average quality?

In [17]:
machine_A = [88, 85, 87, 90, 89, 88, 86, 87]
machine_B = [82, 84, 83, 81, 80, 83, 82, 84]
machine_C = [91, 90, 92, 93, 94, 92, 91, 93]

f_stats3, p_value3 = f_oneway(machine_A, machine_B, machine_C)
print (f_stats3, p_value3)
alpha = 0.05
null_hypothesis = "the mean doesn't differ significantly between machines"
alternative_hypothesis = "the mean differs significantly between machines"

if p_value3< alpha:
    print (f"based on the current evidence {alternative_hypothesis}")
else:
    print (f"based on the current evidence {null_hypothesis}")

88.80626780626768 5.678487937229093e-11
based on the current evidence the mean differs significantly between machines

In [18]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
# checking the mean difference between machines
# Combine data and labels
scores_data = machine_A + machine_B + machine_C
machines = ['A']*len(machine_A) + ['B']*len(machine_B) + ['C']*len(machine_C)

df = pd.DataFrame({'machine': machines, 'scores': scores_data})

# Tukey HSD test
tukey = pairwise_tukeyhsd(endog=df['scores'], groups=df['machine'], alpha=0.05)
print(tukey)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj  lower   upper  reject
---------------------------------------------------
     A      B   -5.125   0.0 -6.9467 -3.3033   True
     A      C      4.5   0.0  2.6783  6.3217   True
     B      C    9.625   0.0  7.8033 11.4467   True
---------------------------------------------------

### Question 5
Diet Plan vs Weight Loss Scenario: Four diet plans (Keto, Paleo, Vegan, and Mediterranean) were followed for 8 weeks. The weight loss (in kg) of participants was recorded. Task: Use ANOVA in Python to test if diet type affects weight loss. Question: Is there a significant difference in mean weight loss among the four diets?

In [19]:
data = {
    'diet': ['Keto']*6 + ['Paleo']*6 + ['Vegan']*6 + ['Mediterranean']*6,
    'weight_loss': [6, 5, 7, 8, 6, 7, 5, 6, 4, 5, 6, 5, 3, 4, 2, 4, 3, 2, 5, 6, 7, 6, 8, 7]
}

df3 = pd.DataFrame(data)
df3.head()

   diet  weight_loss
0  Keto            6
1  Keto            5
2  Keto            7
3  Keto            8
4  Keto            6

In [20]:
formula3 = 'weight_loss ~ C(diet)'

In [21]:
lm3 = ols(formula3, df3).fit()
lm3

In [22]:
table3 = sm.stats.anova_lm(lm3,typ=2)
table3

             sum_sq    df          F    PR(>F)
C(diet)   49.125000   3.0  18.364486  0.000006
Residual  17.833333  20.0        NaN       NaN

In [23]:
alpha = 0.05
p_value = table3['PR(>F)'][0]

if p_value < alpha:
    print("based on the current evidence there is a significant difference in mean weight loss among the four diets.")
else:
    print("based on the current evidence there is no significant difference in mean weight loss among the four diets.")

based on the current evidence there is a significant difference in mean weight loss among the four diets.

C:\Users\Convenience\AppData\Local\Temp\ipykernel_5760\3630046848.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  p_value = table3['PR(>F)'][0]